---
- name: enable shh
  hosts: all
  gather_facts: false
  connection: local
 
  tasks:
      - name: enable_ssh
        telnet:
          user: cisco
          password: cisco
          login_prompt: "Username: "
          prompts:
            - "[>|#]"
          command:
            - term le 0
            - conf t
            - ip domain-name lab.local
            - crypto key generate rsa modulus 1024
            - ip ssh version 2
            - exit
            - wr mem
            - exit
        when: ssh_listen|failed
