- name: run show version on remote devices
  hosts: all
  gather_facts: no
  connection: network_cli  
  tasks:
    -name: Global config settings
      ios_config:
           lines:
      - vtp mode transparent
      register: show_result
